### PR TITLE
fix(graphcache): Prevent offlineExchange from issuing duplicate operations

### LINKED ISSUE #3093: Using `graphcache@5.0.0` or 6 the cache in the default storage is not loaded anymore on the first page load
After upgrading from 4 to 5 (or 6) `@urql/exchange-graphcache` doing some tests with a fake delay on the backend I discovered that when I refresh the page (F5 or Ctrl+R) the cache present in the IndexedDB is not used.

**The REPL** (with SvelteKit too) is here: https://codesandbox.io/p/sandbox/romantic-feather-xmc826

**Steps**:

1. Go to https://xmc826-5173.csb.app/todos

1. the todos are downloaded, showed and stored in the IndexedDB after 3 seconds of [fake delay on the server resolver](https://codesandbox.io/p/sandbox/apollo-server-urql-svelte-crud-h1pcl?file=%2Fschema.js&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A132%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A132%7D%5D)

1. Click on the reload button in the navbar (or the browser's one)

1. The "Loading listStore..." message appears during the 3 fake delay seconds

1. I expect instead to see the todos immediately (during the `cache-and-network` call which is still happening)

If I rollback only `"@urql/exchange-graphcache"` to `"4.4.3"` this "cold cache" behavior works again.

**What could be causing the problem?**

Thank you in advance.

### Urql version

[package.json](https://codesandbox.io/p/sandbox/romantic-feather-xmc826?selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A19%7D%5D&file=%2Fpackage.json)

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kitten**
Follow-up to #3199
Resolves #3093

## Set of changes

- Add a crude teardown+seen routine to `failedQueue` in `offlineExchange`'s `flushQueue`

### CODE REVIEW

**Comment by frederikhors** [comment]
I forgot to write here too that this still doesn't fix https://github.com/urql-graphql/urql/issues/3093 as is unfortunately.

**Comment by kitten** [comment]
@frederikhors: Should be fixed now. In short, coming back to this, I think it's best to just force the flushed operations to always use `cache-first`.

**Comment by frederikhors** [comment]
@kitten thank you very much. I'll try in an hour-ish.

**Comment by frederikhors** [comment]
I'm trying right now...

**Comment by frederikhors** [comment]
Please do not release the others, give me 5 minutes.

**Comment by frederikhors** [comment]
Ok. I tried. It works, but.

The cached data is used on the cold load now.

The are no multiple requests for the same call.

But I realized that now on cold start on page reload there is no longer the loading indicator I had before, using the following custom exchange:

```ts
const pendingRequestsExchange: Exchange = ({ forward }) => {
  function before(op: Operation) {
    if (op.kind === 'subscription') return;
    if (op.kind && op.kind === 'teardown') {
      console.log('call deletePendingRequest');
      deletePendingRequest(op.key);
    } else {
      console.log('call addPendingRequest');
      addPendingRequest(op.key);
    }
  }
  function after(op: OperationResult) {
    deletePendingRequest(op.operation.key);
  }
  return (ops$) => {
    const forward$ = pipe(ops$, tap(before));
    return pipe(forward(forward$), tap(after));
  };
};
```

This is happening because it now calls immediately `addPendingRequest` and `deletePendingRequest` without waiting the pending request.

This is not what I expect during the cold start with the cache data already there.

**Comment by frederikhors** [comment]
The amazing @kitten is working on this [here](https://github.com/urql-graphql/urql/pull/3200).

With the latest commit the things are working now, except [this](https://github.com/urql-graphql/urql/pull/3200#issuecomment-1569845321):

REPRODUCTION: https://codesandbox.io/p/sandbox/issue-urql-6-duplicated-requests-forked-0ybcue.

Steps:

1. click on "Todos list"

1. open the browser dev tools

1. reload the page

1. see in the console `call addPendingRequest` and immediately (not after the fake delay of the server) `call deletePendingRequest`

**Comment by frederikhors** [comment]
Added reproduction for the latest issue here: https://github.com/urql-graphql/urql/issues/3093#issuecomment-1569869068.

**Comment by kitten** [comment]
@frederikhors: I can't debug your exchange for you, but you will have to adjust your `after` call to be more precise. If this is just to keep track of global loading states, I'd suggest to be more accurate with `cache-only` operations in `after` and/or maybe adding a delay or debounce here.

**Comment by frederikhors** [comment]
This new behavior is reproduced here: https://codesandbox.io/p/sandbox/issue-urql-6-duplicated-requests-forked-0ybcue. TOu can see the `after` call is never issued.

**Pull request merged**
