### PR TITLE
(DRAFT) SolidJS bindings

### PR DESCRIPTION
**Pull request by gksander**
**This PR serves as a didactic to discuss the feasibility of solidjs bindings for urql.**

This branch contains initial prototypes for `createQuery` and `createMutation` methods that (attempt) to conform to both urql _and_ solidjs paradigms.

## Existing functionality

- `createQuery` and `createMutation` initial functionality. Both leverage solid's `createResource` API, since that appears to be the only out-of-the-box way to trigger suspense boundaries.
- Type-safety. Argument types, but also sprinkles some type-safety into loosely-typed solid APIs (E.g., the `createResource()[1].refetch` is not typed, so I shimmed those in.)
- Reactive using solid's notion of "signals", and standard wonka tools. Changing a query argument will trigger a refetch, etc.

## Outstanding tasks

- [ ] Unit tests... this is stumping me. Solid's `createResource` is throwing in node environment when running jest tests, so there's an immediate roadblock when trying to unit-test this functionality.
- [ ] E2E tests to properly test suspense.
- [ ] Support for subscriptions.
- [ ] Documentation.

### CODE REVIEW

**Comment by edemaine** [comment]
Regarding Node tests: did you try running Node with tue `browser` condition, via `node -C browser`? What error are you getting? Feel free to come ask questions in the Solid Discord!

**Comment by gksander** [comment]
@edemaine I have not tried `-C browser`! I'll try to carve out some time to dust off this PR and see if I can get the tests working. I found my way into the Solid Discord server, so if I run into more bumps, I'll reach out in there to see if I can get some help!

**Comment by tbillington** [comment]
If you're able to commit some example tests I can try to help them build.

**Comment by gksander** [comment]
@tbillington I appreciate that! I just pushed up a "dummy" test in `packages/solid-urql/src/createQuery.test.ts`. That test will throw

> TypeError: Cannot read properties of undefined (reading 'id')

that I believe stems from the `createResource` call that `createQuery` uses under the hood, but I haven't had a chance to dive into the Solid source code to see where that stems from.

To test this out, just pull down this branch, `cd packages/solid-urql` and run `yarn test` – should throw something similar to what I have above.

**Comment by tbillington** [comment]
Reasonable confident this is what's being hit.

https://github.com/solidjs/solid/blob/74c9871e623ddb0227964ab7d013b1bde6fdd2c6/packages/solid/src/server/rendering.ts#L326

So [`sharedConfig` is never being initialised with a `context` property](https://github.com/solidjs/solid/blob/74c9871e623ddb0227964ab7d013b1bde6fdd2c6/packages/solid/src/server/rendering.ts#L50).

I tried wrapping the test logic within `createRoot`, since the solid API docs mention all solid code needs to function in that context (usually done for you by `render()`), but that didn't help!

Changing your test code to this allows the test to run and pass. May be a good intermediate step until a better solution is found.

```typescript
import { sharedConfig } from 'solid-js';
import { createQuery } from './createQuery';

describe('createQuery', () => {
  beforeEach(() => {
    sharedConfig.context = { count: 0, id: 'a' };
  });

  it('does a thing', () => {
    createQuery(() => ({
      query: `{ test }`,
    }));

    expect(true).toBeTruthy();
  });
});
```

**Comment by gksander** [comment]
@Krymancer That'd be great! I unfortunately haven't had the time to work on this in the last couple of weeks, but if you want to fork off of this and see what progress you can make – I'm happy to merge whatever progress you can make into this branch!

**Comment by kitten** [comment]
Closing for now! I'm looking to find time for this soon (and we have another `solid-urql` library already to compare with), however, I don't want to keep this open until then to give off the impression that it's always just around the corner ✌️ 😅 
I'll keep the branch intact though!

**Comment by frederikhors** [comment]
Any news about SolidJS integration? Solid is a real beast!

**Pull request closed without merging**
